# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

platform :ios, "9.0"
use_frameworks!

def pods_base

	pod 'SwiftyJSON'
	pod 'Alamofire'
    pod 'RealmSwift'
    pod 'SWTableViewCell'
    pod 'Socket.IO-Client-Swift'
    pod 'ActionSheetPicker-3.0'
    pod 'SwiftSpinner'
    pod 'NVActivityIndicatorView'
    pod 'UrbanAirship-iOS-SDK'

end


target 'EnUn2x3' do
    pods_base
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
