platform :ios, "8.1"
use_frameworks!


def pods_base
    
    pod 'MaterialKit', :git => 'https://github.com/reesemclean/MaterialKit', :branch => 'swift_2'
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git', :branch => 'swift2'
    pod 'Alamofire', '~> 3.5'
    pod 'RealmSwift'
    pod 'SWTableViewCell'
    pod 'Socket.IO-Client-Swift', :git => 'https://github.com/socketio/socket.io-client-swift.git', :branch => 'swift2.3'

end


target 'EnUn2x3 Admin' do
    pods_base
end

target 'EnUn2x3 AdminTests' do
    pods_base
end

target 'EnUn2x3 AdminUITests' do
    pods_base
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '2.3'
            config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = 'E84E364GC2/'
            config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
        end
    end
end
